// Generated — do not hand-edit
import type { HighlightVideo } from '../types'

/**
 * Auto-curated CBS Sports Golazo highlight cuts for esp1 2026-27, keyed by match id.
 *
 * GENERATED by scripts/curate-club-videos.ts — do not edit by hand. Entries are
 * appended as Golazo publishes a full-match cut that clears every one of the
 * curator's deterministic gates; nothing is ever edited or removed.
 *
 * No entry carries `durationSeconds`, and none ever should: that omission is
 * what keeps a runtime badge off club matches.
 */
export const esp1_2026_videos: Record<string, HighlightVideo[]> = {}
