/**
 * GENERATED by scripts/espn-nations.ts. Do not edit by hand.
 * Fixtures are accepted only after matching unl-2026-official.ts.
 */
import type { Tournament } from '../types'
import { pickNationalTeams } from '../national-teams'
import { unl2026Videos } from './unl-2026-videos'

const generated: Omit<Tournament, 'teams'> = {
  "id": "unl-2026",
  "name": "UEFA Nations League 2026/27",
  "year": 2026,
  "advancingRanks": [
    1,
    2
  ],
  "tiebreakers": [
    "head-to-head",
    "goal-difference",
    "goals-for",
    "away-goals",
    "wins",
    "away-wins",
    "disciplinary",
    "access-list"
  ],
  "groups": [
    {
      "id": "A1",
      "label": "Group A1",
      "sectionId": "A",
      "teams": [
        "ITA",
        "BEL",
        "TUR",
        "FRA"
      ]
    },
    {
      "id": "A2",
      "label": "Group A2",
      "sectionId": "A",
      "teams": [
        "NED",
        "GRE",
        "GER",
        "SRB"
      ]
    },
    {
      "id": "A3",
      "label": "Group A3",
      "sectionId": "A",
      "teams": [
        "ESP",
        "ENG",
        "CZE",
        "CRO"
      ]
    },
    {
      "id": "A4",
      "label": "Group A4",
      "sectionId": "A",
      "teams": [
        "NOR",
        "DEN",
        "POR",
        "WAL"
      ]
    },
    {
      "id": "B1",
      "label": "Group B1",
      "sectionId": "B",
      "teams": [
        "MKD",
        "SVN",
        "SUI",
        "SCO"
      ]
    },
    {
      "id": "B2",
      "label": "Group B2",
      "sectionId": "B",
      "teams": [
        "UKR",
        "HUN",
        "GEO",
        "NIR"
      ]
    },
    {
      "id": "B3",
      "label": "Group B3",
      "sectionId": "B",
      "teams": [
        "ISR",
        "AUT",
        "IRL",
        "KOS"
      ]
    },
    {
      "id": "B4",
      "label": "Group B4",
      "sectionId": "B",
      "teams": [
        "BIH",
        "SWE",
        "POL",
        "ROU"
      ]
    },
    {
      "id": "C1",
      "label": "Group C1",
      "sectionId": "C",
      "teams": [
        "FIN",
        "BLR",
        "ALB",
        "SMR"
      ]
    },
    {
      "id": "C2",
      "label": "Group C2",
      "sectionId": "C",
      "teams": [
        "CYP",
        "LVA",
        "ARM",
        "MNE"
      ]
    },
    {
      "id": "C3",
      "label": "Group C3",
      "sectionId": "C",
      "teams": [
        "FRO",
        "SVK",
        "MDA",
        "KAZ"
      ]
    },
    {
      "id": "C4",
      "label": "Group C4",
      "sectionId": "C",
      "teams": [
        "EST",
        "BUL",
        "ISL",
        "LUX"
      ]
    },
    {
      "id": "D1",
      "label": "Group D1",
      "sectionId": "D",
      "teams": [
        "MLT",
        "AND",
        "GIB"
      ]
    },
    {
      "id": "D2",
      "label": "Group D2",
      "sectionId": "D",
      "teams": [
        "LTU",
        "AZE",
        "LIE"
      ]
    }
  ],
  "groupSections": [
    {
      "id": "A",
      "label": "League A",
      "groupIds": [
        "A1",
        "A2",
        "A3",
        "A4"
      ]
    },
    {
      "id": "B",
      "label": "League B",
      "groupIds": [
        "B1",
        "B2",
        "B3",
        "B4"
      ]
    },
    {
      "id": "C",
      "label": "League C",
      "groupIds": [
        "C1",
        "C2",
        "C3",
        "C4"
      ]
    },
    {
      "id": "D",
      "label": "League D",
      "groupIds": [
        "D1",
        "D2"
      ]
    }
  ],
  "qualificationSections": [
    {
      "sectionId": "A",
      "rules": [
        {
          "groupRank": 1,
          "outcome": {
            "kind": "qualify",
            "label": "Quarter-finals"
          }
        },
        {
          "groupRank": 2,
          "outcome": {
            "kind": "qualify",
            "label": "Quarter-finals"
          }
        },
        {
          "groupRank": 3,
          "outcome": {
            "kind": "stay",
            "label": "Stay in League A"
          },
          "crossGroup": {
            "top": 2,
            "topOutcome": {
              "kind": "stay",
              "label": "Stay in League A"
            },
            "bottomOutcome": {
              "kind": "playoff",
              "label": "A/B play-off"
            }
          }
        },
        {
          "groupRank": 4,
          "outcome": {
            "kind": "relegate",
            "label": "Relegated to League B"
          },
          "crossGroup": {
            "top": 2,
            "topOutcome": {
              "kind": "playoff",
              "label": "A/B play-off"
            },
            "bottomOutcome": {
              "kind": "relegate",
              "label": "Relegated to League B"
            }
          }
        }
      ]
    },
    {
      "sectionId": "B",
      "rules": [
        {
          "groupRank": 1,
          "outcome": {
            "kind": "promote",
            "label": "Promoted to League A"
          }
        },
        {
          "groupRank": 2,
          "outcome": {
            "kind": "playoff",
            "label": "A/B play-off"
          }
        },
        {
          "groupRank": 3,
          "outcome": {
            "kind": "stay",
            "label": "Stay in League B"
          }
        },
        {
          "groupRank": 4,
          "outcome": {
            "kind": "playoff",
            "label": "B/C play-off"
          }
        }
      ]
    },
    {
      "sectionId": "C",
      "rules": [
        {
          "groupRank": 1,
          "outcome": {
            "kind": "promote",
            "label": "Promoted to League B"
          }
        },
        {
          "groupRank": 2,
          "outcome": {
            "kind": "playoff",
            "label": "B/C play-off"
          }
        },
        {
          "groupRank": 3,
          "outcome": {
            "kind": "stay",
            "label": "Stay in League C"
          }
        },
        {
          "groupRank": 4,
          "outcome": {
            "kind": "stay",
            "label": "Stay in League C"
          }
        }
      ]
    },
    {
      "sectionId": "D",
      "rules": [
        {
          "groupRank": 1,
          "outcome": {
            "kind": "promote",
            "label": "Promoted to League C"
          }
        },
        {
          "groupRank": 2,
          "outcome": {
            "kind": "promote",
            "label": "Promoted to League C"
          }
        },
        {
          "groupRank": 3,
          "outcome": {
            "kind": "promote",
            "label": "Promoted to League C"
          }
        }
      ]
    }
  ],
  "groupMatches": [
    {
      "id": "unl-401861047",
      "group": "D1",
      "matchday": 1,
      "date": "2026-09-24",
      "kickoff": "2026-09-24T16:00Z",
      "home": "AND",
      "away": "MLT",
      "liveStatus": {
        "kind": "live"
      }
    },
    {
      "id": "unl-401861041",
      "group": "A2",
      "matchday": 1,
      "date": "2026-09-24",
      "kickoff": "2026-09-24T18:45Z",
      "home": "NED",
      "away": "GER"
    },
    {
      "id": "unl-401861042",
      "group": "A2",
      "matchday": 1,
      "date": "2026-09-24",
      "kickoff": "2026-09-24T18:45Z",
      "home": "SRB",
      "away": "GRE"
    },
    {
      "id": "unl-401861043",
      "group": "D2",
      "matchday": 1,
      "date": "2026-09-24",
      "kickoff": "2026-09-24T18:45Z",
      "home": "LIE",
      "away": "LTU"
    },
    {
      "id": "unl-401861044",
      "group": "A4",
      "matchday": 1,
      "date": "2026-09-24",
      "kickoff": "2026-09-24T18:45Z",
      "home": "POR",
      "away": "WAL"
    },
    {
      "id": "unl-401861045",
      "group": "B3",
      "matchday": 1,
      "date": "2026-09-24",
      "kickoff": "2026-09-24T18:45Z",
      "home": "KOS",
      "away": "IRL"
    },
    {
      "id": "unl-401861046",
      "group": "A4",
      "matchday": 1,
      "date": "2026-09-24",
      "kickoff": "2026-09-24T18:45Z",
      "home": "NOR",
      "away": "DEN"
    },
    {
      "id": "unl-401861048",
      "group": "B3",
      "matchday": 1,
      "date": "2026-09-24",
      "kickoff": "2026-09-24T18:45Z",
      "home": "AUT",
      "away": "ISR"
    },
    {
      "id": "unl-401861049",
      "group": "B2",
      "matchday": 1,
      "date": "2026-09-25",
      "kickoff": "2026-09-25T16:00Z",
      "home": "GEO",
      "away": "NIR"
    },
    {
      "id": "unl-401861050",
      "group": "C2",
      "matchday": 1,
      "date": "2026-09-25",
      "kickoff": "2026-09-25T16:00Z",
      "home": "ARM",
      "away": "LVA"
    },
    {
      "id": "unl-401861051",
      "group": "B4",
      "matchday": 1,
      "date": "2026-09-25",
      "kickoff": "2026-09-25T18:45Z",
      "home": "SWE",
      "away": "ROU"
    },
    {
      "id": "unl-401861052",
      "group": "A1",
      "matchday": 1,
      "date": "2026-09-25",
      "kickoff": "2026-09-25T18:45Z",
      "home": "ITA",
      "away": "BEL"
    },
    {
      "id": "unl-401861053",
      "group": "A1",
      "matchday": 1,
      "date": "2026-09-25",
      "kickoff": "2026-09-25T18:45Z",
      "home": "TUR",
      "away": "FRA"
    },
    {
      "id": "unl-401861054",
      "group": "B2",
      "matchday": 1,
      "date": "2026-09-25",
      "kickoff": "2026-09-25T18:45Z",
      "home": "HUN",
      "away": "UKR"
    },
    {
      "id": "unl-401861055",
      "group": "B4",
      "matchday": 1,
      "date": "2026-09-25",
      "kickoff": "2026-09-25T18:45Z",
      "home": "POL",
      "away": "BIH"
    },
    {
      "id": "unl-401861056",
      "group": "C2",
      "matchday": 1,
      "date": "2026-09-25",
      "kickoff": "2026-09-25T18:45Z",
      "home": "MNE",
      "away": "CYP"
    },
    {
      "id": "unl-401861057",
      "group": "B1",
      "matchday": 1,
      "date": "2026-09-26",
      "kickoff": "2026-09-26T13:00Z",
      "home": "SVN",
      "away": "SCO"
    },
    {
      "id": "unl-401861058",
      "group": "C4",
      "matchday": 1,
      "date": "2026-09-26",
      "kickoff": "2026-09-26T16:00Z",
      "home": "ISL",
      "away": "EST"
    },
    {
      "id": "unl-401861059",
      "group": "C1",
      "matchday": 1,
      "date": "2026-09-26",
      "kickoff": "2026-09-26T16:00Z",
      "home": "SMR",
      "away": "FIN"
    },
    {
      "id": "unl-401861060",
      "group": "C3",
      "matchday": 1,
      "date": "2026-09-26",
      "kickoff": "2026-09-26T16:00Z",
      "home": "FRO",
      "away": "KAZ"
    },
    {
      "id": "unl-401861061",
      "group": "C4",
      "matchday": 1,
      "date": "2026-09-26",
      "kickoff": "2026-09-26T16:00Z",
      "home": "BUL",
      "away": "LUX"
    },
    {
      "id": "unl-401861062",
      "group": "C1",
      "matchday": 1,
      "date": "2026-09-26",
      "kickoff": "2026-09-26T18:45Z",
      "home": "ALB",
      "away": "BLR"
    },
    {
      "id": "unl-401861063",
      "group": "A3",
      "matchday": 1,
      "date": "2026-09-26",
      "kickoff": "2026-09-26T18:45Z",
      "home": "CZE",
      "away": "CRO"
    },
    {
      "id": "unl-401861064",
      "group": "C3",
      "matchday": 1,
      "date": "2026-09-26",
      "kickoff": "2026-09-26T18:45Z",
      "home": "SVK",
      "away": "MDA"
    },
    {
      "id": "unl-401861065",
      "group": "B1",
      "matchday": 1,
      "date": "2026-09-26",
      "kickoff": "2026-09-26T18:45Z",
      "home": "MKD",
      "away": "SUI"
    },
    {
      "id": "unl-401861066",
      "group": "A3",
      "matchday": 1,
      "date": "2026-09-26",
      "kickoff": "2026-09-26T18:45Z",
      "home": "ENG",
      "away": "ESP"
    },
    {
      "id": "unl-401861067",
      "group": "D2",
      "matchday": 2,
      "date": "2026-09-27",
      "kickoff": "2026-09-27T13:00Z",
      "home": "LTU",
      "away": "AZE"
    },
    {
      "id": "unl-401861068",
      "group": "A2",
      "matchday": 2,
      "date": "2026-09-27",
      "kickoff": "2026-09-27T16:00Z",
      "home": "SRB",
      "away": "NED"
    },
    {
      "id": "unl-401861069",
      "group": "D1",
      "matchday": 2,
      "date": "2026-09-27",
      "kickoff": "2026-09-27T16:00Z",
      "home": "GIB",
      "away": "AND"
    },
    {
      "id": "unl-401861070",
      "group": "A4",
      "matchday": 2,
      "date": "2026-09-27",
      "kickoff": "2026-09-27T16:00Z",
      "home": "DEN",
      "away": "WAL"
    },
    {
      "id": "unl-401861071",
      "group": "B3",
      "matchday": 2,
      "date": "2026-09-27",
      "kickoff": "2026-09-27T16:00Z",
      "home": "AUT",
      "away": "KOS"
    },
    {
      "id": "unl-401861072",
      "group": "B3",
      "matchday": 2,
      "date": "2026-09-27",
      "kickoff": "2026-09-27T18:45Z",
      "home": "ISR",
      "away": "IRL"
    },
    {
      "id": "unl-401861073",
      "group": "A4",
      "matchday": 2,
      "date": "2026-09-27",
      "kickoff": "2026-09-27T18:45Z",
      "home": "NOR",
      "away": "POR"
    },
    {
      "id": "unl-401861074",
      "group": "A2",
      "matchday": 2,
      "date": "2026-09-27",
      "kickoff": "2026-09-27T18:45Z",
      "home": "GER",
      "away": "GRE"
    },
    {
      "id": "unl-401861075",
      "group": "B2",
      "matchday": 2,
      "date": "2026-09-28",
      "kickoff": "2026-09-28T16:00Z",
      "home": "GEO",
      "away": "UKR"
    },
    {
      "id": "unl-401861076",
      "group": "C2",
      "matchday": 2,
      "date": "2026-09-28",
      "kickoff": "2026-09-28T16:00Z",
      "home": "ARM",
      "away": "MNE"
    },
    {
      "id": "unl-401861082",
      "group": "C2",
      "matchday": 2,
      "date": "2026-09-28",
      "kickoff": "2026-09-28T16:00Z",
      "home": "LVA",
      "away": "CYP"
    },
    {
      "id": "unl-401861077",
      "group": "A1",
      "matchday": 2,
      "date": "2026-09-28",
      "kickoff": "2026-09-28T18:45Z",
      "home": "TUR",
      "away": "ITA"
    },
    {
      "id": "unl-401861078",
      "group": "B4",
      "matchday": 2,
      "date": "2026-09-28",
      "kickoff": "2026-09-28T18:45Z",
      "home": "ROU",
      "away": "BIH"
    },
    {
      "id": "unl-401861079",
      "group": "B2",
      "matchday": 2,
      "date": "2026-09-28",
      "kickoff": "2026-09-28T18:45Z",
      "home": "NIR",
      "away": "HUN"
    },
    {
      "id": "unl-401861080",
      "group": "B4",
      "matchday": 2,
      "date": "2026-09-28",
      "kickoff": "2026-09-28T18:45Z",
      "home": "SWE",
      "away": "POL"
    },
    {
      "id": "unl-401861081",
      "group": "A1",
      "matchday": 2,
      "date": "2026-09-28",
      "kickoff": "2026-09-28T18:45Z",
      "home": "BEL",
      "away": "FRA"
    },
    {
      "id": "unl-401861089",
      "group": "C1",
      "matchday": 2,
      "date": "2026-09-29",
      "kickoff": "2026-09-29T16:00Z",
      "home": "FIN",
      "away": "BLR"
    },
    {
      "id": "unl-401861090",
      "group": "C3",
      "matchday": 2,
      "date": "2026-09-29",
      "kickoff": "2026-09-29T16:00Z",
      "home": "MDA",
      "away": "FRO"
    },
    {
      "id": "unl-401861083",
      "group": "C4",
      "matchday": 2,
      "date": "2026-09-29",
      "kickoff": "2026-09-29T18:45Z",
      "home": "BUL",
      "away": "EST"
    },
    {
      "id": "unl-401861084",
      "group": "A3",
      "matchday": 2,
      "date": "2026-09-29",
      "kickoff": "2026-09-29T18:45Z",
      "home": "ESP",
      "away": "CRO"
    },
    {
      "id": "unl-401861085",
      "group": "C3",
      "matchday": 2,
      "date": "2026-09-29",
      "kickoff": "2026-09-29T18:45Z",
      "home": "SVK",
      "away": "KAZ"
    },
    {
      "id": "unl-401861086",
      "group": "C4",
      "matchday": 2,
      "date": "2026-09-29",
      "kickoff": "2026-09-29T18:45Z",
      "home": "LUX",
      "away": "ISL"
    },
    {
      "id": "unl-401861087",
      "group": "B1",
      "matchday": 2,
      "date": "2026-09-29",
      "kickoff": "2026-09-29T18:45Z",
      "home": "SVN",
      "away": "MKD"
    },
    {
      "id": "unl-401861088",
      "group": "C1",
      "matchday": 2,
      "date": "2026-09-29",
      "kickoff": "2026-09-29T18:45Z",
      "home": "SMR",
      "away": "ALB"
    },
    {
      "id": "unl-401861091",
      "group": "B1",
      "matchday": 2,
      "date": "2026-09-29",
      "kickoff": "2026-09-29T18:45Z",
      "home": "SCO",
      "away": "SUI"
    },
    {
      "id": "unl-401861092",
      "group": "A3",
      "matchday": 2,
      "date": "2026-09-29",
      "kickoff": "2026-09-29T18:45Z",
      "home": "CZE",
      "away": "ENG"
    },
    {
      "id": "unl-401861093",
      "group": "D2",
      "matchday": 3,
      "date": "2026-10-01",
      "kickoff": "2026-10-01T16:00Z",
      "home": "AZE",
      "away": "LIE"
    },
    {
      "id": "unl-401861094",
      "group": "B3",
      "matchday": 3,
      "date": "2026-10-01",
      "kickoff": "2026-10-01T18:45Z",
      "home": "IRL",
      "away": "AUT"
    },
    {
      "id": "unl-401861095",
      "group": "B3",
      "matchday": 3,
      "date": "2026-10-01",
      "kickoff": "2026-10-01T18:45Z",
      "home": "ISR",
      "away": "KOS"
    },
    {
      "id": "unl-401861096",
      "group": "A4",
      "matchday": 3,
      "date": "2026-10-01",
      "kickoff": "2026-10-01T18:45Z",
      "home": "DEN",
      "away": "POR"
    },
    {
      "id": "unl-401861097",
      "group": "A2",
      "matchday": 3,
      "date": "2026-10-01",
      "kickoff": "2026-10-01T18:45Z",
      "home": "GER",
      "away": "SRB"
    },
    {
      "id": "unl-401861098",
      "group": "A2",
      "matchday": 3,
      "date": "2026-10-01",
      "kickoff": "2026-10-01T18:45Z",
      "home": "GRE",
      "away": "NED"
    },
    {
      "id": "unl-401861099",
      "group": "D1",
      "matchday": 3,
      "date": "2026-10-01",
      "kickoff": "2026-10-01T18:45Z",
      "home": "MLT",
      "away": "GIB"
    },
    {
      "id": "unl-401861100",
      "group": "A4",
      "matchday": 3,
      "date": "2026-10-01",
      "kickoff": "2026-10-01T18:45Z",
      "home": "WAL",
      "away": "NOR"
    },
    {
      "id": "unl-401861101",
      "group": "C3",
      "matchday": 3,
      "date": "2026-10-02",
      "kickoff": "2026-10-02T14:00Z",
      "home": "KAZ",
      "away": "MDA"
    },
    {
      "id": "unl-401861104",
      "group": "C2",
      "matchday": 3,
      "date": "2026-10-02",
      "kickoff": "2026-10-02T16:00Z",
      "home": "CYP",
      "away": "ARM"
    },
    {
      "id": "unl-401861105",
      "group": "C2",
      "matchday": 3,
      "date": "2026-10-02",
      "kickoff": "2026-10-02T16:00Z",
      "home": "LVA",
      "away": "MNE"
    },
    {
      "id": "unl-401861102",
      "group": "B2",
      "matchday": 3,
      "date": "2026-10-02",
      "kickoff": "2026-10-02T18:45Z",
      "home": "HUN",
      "away": "GEO"
    },
    {
      "id": "unl-401861103",
      "group": "A1",
      "matchday": 3,
      "date": "2026-10-02",
      "kickoff": "2026-10-02T18:45Z",
      "home": "FRA",
      "away": "ITA"
    },
    {
      "id": "unl-401861106",
      "group": "B2",
      "matchday": 3,
      "date": "2026-10-02",
      "kickoff": "2026-10-02T18:45Z",
      "home": "UKR",
      "away": "NIR"
    },
    {
      "id": "unl-401861107",
      "group": "B4",
      "matchday": 3,
      "date": "2026-10-02",
      "kickoff": "2026-10-02T18:45Z",
      "home": "BIH",
      "away": "SWE"
    },
    {
      "id": "unl-401861108",
      "group": "B4",
      "matchday": 3,
      "date": "2026-10-02",
      "kickoff": "2026-10-02T18:45Z",
      "home": "POL",
      "away": "ROU"
    },
    {
      "id": "unl-401861109",
      "group": "A1",
      "matchday": 3,
      "date": "2026-10-02",
      "kickoff": "2026-10-02T18:45Z",
      "home": "BEL",
      "away": "TUR"
    },
    {
      "id": "unl-401861110",
      "group": "C3",
      "matchday": 3,
      "date": "2026-10-02",
      "kickoff": "2026-10-02T18:45Z",
      "home": "FRO",
      "away": "SVK"
    },
    {
      "id": "unl-401861111",
      "group": "C1",
      "matchday": 3,
      "date": "2026-10-03",
      "kickoff": "2026-10-03T13:00Z",
      "home": "FIN",
      "away": "ALB"
    },
    {
      "id": "unl-401861112",
      "group": "C4",
      "matchday": 3,
      "date": "2026-10-03",
      "kickoff": "2026-10-03T16:00Z",
      "home": "ISL",
      "away": "BUL"
    },
    {
      "id": "unl-401861113",
      "group": "A3",
      "matchday": 3,
      "date": "2026-10-03",
      "kickoff": "2026-10-03T16:00Z",
      "home": "CRO",
      "away": "ENG"
    },
    {
      "id": "unl-401861114",
      "group": "C1",
      "matchday": 3,
      "date": "2026-10-03",
      "kickoff": "2026-10-03T16:00Z",
      "home": "BLR",
      "away": "SMR"
    },
    {
      "id": "unl-401861115",
      "group": "C4",
      "matchday": 3,
      "date": "2026-10-03",
      "kickoff": "2026-10-03T16:00Z",
      "home": "EST",
      "away": "LUX"
    },
    {
      "id": "unl-401861116",
      "group": "B1",
      "matchday": 3,
      "date": "2026-10-03",
      "kickoff": "2026-10-03T18:45Z",
      "home": "MKD",
      "away": "SCO"
    },
    {
      "id": "unl-401861117",
      "group": "B1",
      "matchday": 3,
      "date": "2026-10-03",
      "kickoff": "2026-10-03T18:45Z",
      "home": "SUI",
      "away": "SVN"
    },
    {
      "id": "unl-401861118",
      "group": "A3",
      "matchday": 3,
      "date": "2026-10-03",
      "kickoff": "2026-10-03T18:45Z",
      "home": "ESP",
      "away": "CZE"
    },
    {
      "id": "unl-401861119",
      "group": "D2",
      "matchday": 4,
      "date": "2026-10-04",
      "kickoff": "2026-10-04T13:00Z",
      "home": "AZE",
      "away": "LTU"
    },
    {
      "id": "unl-401861120",
      "group": "D1",
      "matchday": 4,
      "date": "2026-10-04",
      "kickoff": "2026-10-04T16:00Z",
      "home": "MLT",
      "away": "AND"
    },
    {
      "id": "unl-401861121",
      "group": "B3",
      "matchday": 4,
      "date": "2026-10-04",
      "kickoff": "2026-10-04T16:00Z",
      "home": "KOS",
      "away": "AUT"
    },
    {
      "id": "unl-401861122",
      "group": "A2",
      "matchday": 4,
      "date": "2026-10-04",
      "kickoff": "2026-10-04T18:45Z",
      "home": "NED",
      "away": "SRB"
    },
    {
      "id": "unl-401861123",
      "group": "A2",
      "matchday": 4,
      "date": "2026-10-04",
      "kickoff": "2026-10-04T18:45Z",
      "home": "GRE",
      "away": "GER"
    },
    {
      "id": "unl-401861124",
      "group": "B3",
      "matchday": 4,
      "date": "2026-10-04",
      "kickoff": "2026-10-04T18:45Z",
      "home": "IRL",
      "away": "ISR"
    },
    {
      "id": "unl-401861125",
      "group": "A4",
      "matchday": 4,
      "date": "2026-10-04",
      "kickoff": "2026-10-04T18:45Z",
      "home": "WAL",
      "away": "DEN"
    },
    {
      "id": "unl-401861126",
      "group": "A4",
      "matchday": 4,
      "date": "2026-10-04",
      "kickoff": "2026-10-04T18:45Z",
      "home": "POR",
      "away": "NOR"
    },
    {
      "id": "unl-401861127",
      "group": "C2",
      "matchday": 4,
      "date": "2026-10-05",
      "kickoff": "2026-10-05T16:00Z",
      "home": "CYP",
      "away": "LVA"
    },
    {
      "id": "unl-401861128",
      "group": "B4",
      "matchday": 4,
      "date": "2026-10-05",
      "kickoff": "2026-10-05T18:45Z",
      "home": "ROU",
      "away": "SWE"
    },
    {
      "id": "unl-401861129",
      "group": "A1",
      "matchday": 4,
      "date": "2026-10-05",
      "kickoff": "2026-10-05T18:45Z",
      "home": "FRA",
      "away": "BEL"
    },
    {
      "id": "unl-401861130",
      "group": "C2",
      "matchday": 4,
      "date": "2026-10-05",
      "kickoff": "2026-10-05T18:45Z",
      "home": "MNE",
      "away": "ARM"
    },
    {
      "id": "unl-401861131",
      "group": "A1",
      "matchday": 4,
      "date": "2026-10-05",
      "kickoff": "2026-10-05T18:45Z",
      "home": "ITA",
      "away": "TUR"
    },
    {
      "id": "unl-401861132",
      "group": "B2",
      "matchday": 4,
      "date": "2026-10-05",
      "kickoff": "2026-10-05T18:45Z",
      "home": "NIR",
      "away": "GEO"
    },
    {
      "id": "unl-401861133",
      "group": "B4",
      "matchday": 4,
      "date": "2026-10-05",
      "kickoff": "2026-10-05T18:45Z",
      "home": "BIH",
      "away": "POL"
    },
    {
      "id": "unl-401861134",
      "group": "B2",
      "matchday": 4,
      "date": "2026-10-05",
      "kickoff": "2026-10-05T18:45Z",
      "home": "UKR",
      "away": "HUN"
    },
    {
      "id": "unl-401861135",
      "group": "C3",
      "matchday": 4,
      "date": "2026-10-06",
      "kickoff": "2026-10-06T14:00Z",
      "home": "KAZ",
      "away": "FRO"
    },
    {
      "id": "unl-401861136",
      "group": "C4",
      "matchday": 4,
      "date": "2026-10-06",
      "kickoff": "2026-10-06T18:45Z",
      "home": "EST",
      "away": "ISL"
    },
    {
      "id": "unl-401861137",
      "group": "A3",
      "matchday": 4,
      "date": "2026-10-06",
      "kickoff": "2026-10-06T18:45Z",
      "home": "CRO",
      "away": "ESP"
    },
    {
      "id": "unl-401861138",
      "group": "C1",
      "matchday": 4,
      "date": "2026-10-06",
      "kickoff": "2026-10-06T18:45Z",
      "home": "BLR",
      "away": "FIN"
    },
    {
      "id": "unl-401861139",
      "group": "B1",
      "matchday": 4,
      "date": "2026-10-06",
      "kickoff": "2026-10-06T18:45Z",
      "home": "SUI",
      "away": "MKD"
    },
    {
      "id": "unl-401861140",
      "group": "C1",
      "matchday": 4,
      "date": "2026-10-06",
      "kickoff": "2026-10-06T18:45Z",
      "home": "ALB",
      "away": "SMR"
    },
    {
      "id": "unl-401861141",
      "group": "C4",
      "matchday": 4,
      "date": "2026-10-06",
      "kickoff": "2026-10-06T18:45Z",
      "home": "LUX",
      "away": "BUL"
    },
    {
      "id": "unl-401861142",
      "group": "A3",
      "matchday": 4,
      "date": "2026-10-06",
      "kickoff": "2026-10-06T18:45Z",
      "home": "ENG",
      "away": "CZE"
    },
    {
      "id": "unl-401861143",
      "group": "B1",
      "matchday": 4,
      "date": "2026-10-06",
      "kickoff": "2026-10-06T18:45Z",
      "home": "SCO",
      "away": "SVN"
    },
    {
      "id": "unl-401861144",
      "group": "C3",
      "matchday": 4,
      "date": "2026-10-06",
      "kickoff": "2026-10-06T18:45Z",
      "home": "MDA",
      "away": "SVK"
    },
    {
      "id": "unl-401861145",
      "group": "A1",
      "matchday": 5,
      "date": "2026-11-12",
      "kickoff": "2026-11-12T17:00Z",
      "home": "TUR",
      "away": "BEL"
    },
    {
      "id": "unl-401861146",
      "group": "C2",
      "matchday": 5,
      "date": "2026-11-12",
      "kickoff": "2026-11-12T17:00Z",
      "home": "ARM",
      "away": "CYP"
    },
    {
      "id": "unl-401861147",
      "group": "C1",
      "matchday": 5,
      "date": "2026-11-12",
      "kickoff": "2026-11-12T19:45Z",
      "home": "ALB",
      "away": "FIN"
    },
    {
      "id": "unl-401861148",
      "group": "A3",
      "matchday": 5,
      "date": "2026-11-12",
      "kickoff": "2026-11-12T19:45Z",
      "home": "CZE",
      "away": "ESP"
    },
    {
      "id": "unl-401861149",
      "group": "C1",
      "matchday": 5,
      "date": "2026-11-12",
      "kickoff": "2026-11-12T19:45Z",
      "home": "SMR",
      "away": "BLR"
    },
    {
      "id": "unl-401861150",
      "group": "A3",
      "matchday": 5,
      "date": "2026-11-12",
      "kickoff": "2026-11-12T19:45Z",
      "home": "ENG",
      "away": "CRO"
    },
    {
      "id": "unl-401861151",
      "group": "A1",
      "matchday": 5,
      "date": "2026-11-12",
      "kickoff": "2026-11-12T19:45Z",
      "home": "ITA",
      "away": "FRA"
    },
    {
      "id": "unl-401861152",
      "group": "C2",
      "matchday": 5,
      "date": "2026-11-12",
      "kickoff": "2026-11-12T19:45Z",
      "home": "MNE",
      "away": "LVA"
    },
    {
      "id": "unl-401861162",
      "group": "C3",
      "matchday": 5,
      "date": "2026-11-13",
      "kickoff": "2026-11-13T17:00Z",
      "home": "MDA",
      "away": "KAZ"
    },
    {
      "id": "unl-401861153",
      "group": "D2",
      "matchday": 5,
      "date": "2026-11-13",
      "kickoff": "2026-11-13T19:45Z",
      "home": "LIE",
      "away": "AZE"
    },
    {
      "id": "unl-401861154",
      "group": "C4",
      "matchday": 5,
      "date": "2026-11-13",
      "kickoff": "2026-11-13T19:45Z",
      "home": "LUX",
      "away": "EST"
    },
    {
      "id": "unl-401861155",
      "group": "D1",
      "matchday": 5,
      "date": "2026-11-13",
      "kickoff": "2026-11-13T19:45Z",
      "home": "AND",
      "away": "GIB"
    },
    {
      "id": "unl-401861156",
      "group": "B1",
      "matchday": 5,
      "date": "2026-11-13",
      "kickoff": "2026-11-13T19:45Z",
      "home": "SVN",
      "away": "SUI"
    },
    {
      "id": "unl-401861157",
      "group": "C4",
      "matchday": 5,
      "date": "2026-11-13",
      "kickoff": "2026-11-13T19:45Z",
      "home": "BUL",
      "away": "ISL"
    },
    {
      "id": "unl-401861158",
      "group": "A2",
      "matchday": 5,
      "date": "2026-11-13",
      "kickoff": "2026-11-13T19:45Z",
      "home": "SRB",
      "away": "GER"
    },
    {
      "id": "unl-401861159",
      "group": "A2",
      "matchday": 5,
      "date": "2026-11-13",
      "kickoff": "2026-11-13T19:45Z",
      "home": "NED",
      "away": "GRE"
    },
    {
      "id": "unl-401861160",
      "group": "C3",
      "matchday": 5,
      "date": "2026-11-13",
      "kickoff": "2026-11-13T19:45Z",
      "home": "SVK",
      "away": "FRO"
    },
    {
      "id": "unl-401861161",
      "group": "B1",
      "matchday": 5,
      "date": "2026-11-13",
      "kickoff": "2026-11-13T19:45Z",
      "home": "SCO",
      "away": "MKD"
    },
    {
      "id": "unl-401861163",
      "group": "B3",
      "matchday": 5,
      "date": "2026-11-14",
      "kickoff": "2026-11-14T14:00Z",
      "home": "KOS",
      "away": "ISR"
    },
    {
      "id": "unl-401861164",
      "group": "B2",
      "matchday": 5,
      "date": "2026-11-14",
      "kickoff": "2026-11-14T17:00Z",
      "home": "GEO",
      "away": "HUN"
    },
    {
      "id": "unl-401861165",
      "group": "A4",
      "matchday": 5,
      "date": "2026-11-14",
      "kickoff": "2026-11-14T17:00Z",
      "home": "NOR",
      "away": "WAL"
    },
    {
      "id": "unl-401861166",
      "group": "B4",
      "matchday": 5,
      "date": "2026-11-14",
      "kickoff": "2026-11-14T19:45Z",
      "home": "SWE",
      "away": "BIH"
    },
    {
      "id": "unl-401861167",
      "group": "A4",
      "matchday": 5,
      "date": "2026-11-14",
      "kickoff": "2026-11-14T19:45Z",
      "home": "POR",
      "away": "DEN"
    },
    {
      "id": "unl-401861168",
      "group": "B4",
      "matchday": 5,
      "date": "2026-11-14",
      "kickoff": "2026-11-14T19:45Z",
      "home": "ROU",
      "away": "POL"
    },
    {
      "id": "unl-401861169",
      "group": "B2",
      "matchday": 5,
      "date": "2026-11-14",
      "kickoff": "2026-11-14T19:45Z",
      "home": "NIR",
      "away": "UKR"
    },
    {
      "id": "unl-401861170",
      "group": "B3",
      "matchday": 5,
      "date": "2026-11-14",
      "kickoff": "2026-11-14T19:45Z",
      "home": "AUT",
      "away": "IRL"
    },
    {
      "id": "unl-401861171",
      "group": "C2",
      "matchday": 6,
      "date": "2026-11-15",
      "kickoff": "2026-11-15T14:00Z",
      "home": "LVA",
      "away": "ARM"
    },
    {
      "id": "unl-401861172",
      "group": "C2",
      "matchday": 6,
      "date": "2026-11-15",
      "kickoff": "2026-11-15T14:00Z",
      "home": "CYP",
      "away": "MNE"
    },
    {
      "id": "unl-401861173",
      "group": "C1",
      "matchday": 6,
      "date": "2026-11-15",
      "kickoff": "2026-11-15T17:00Z",
      "home": "BLR",
      "away": "ALB"
    },
    {
      "id": "unl-401861174",
      "group": "C1",
      "matchday": 6,
      "date": "2026-11-15",
      "kickoff": "2026-11-15T17:00Z",
      "home": "FIN",
      "away": "SMR"
    },
    {
      "id": "unl-401861175",
      "group": "A3",
      "matchday": 6,
      "date": "2026-11-15",
      "kickoff": "2026-11-15T19:45Z",
      "home": "ESP",
      "away": "ENG"
    },
    {
      "id": "unl-401861176",
      "group": "A1",
      "matchday": 6,
      "date": "2026-11-15",
      "kickoff": "2026-11-15T19:45Z",
      "home": "BEL",
      "away": "ITA"
    },
    {
      "id": "unl-401861177",
      "group": "A1",
      "matchday": 6,
      "date": "2026-11-15",
      "kickoff": "2026-11-15T19:45Z",
      "home": "FRA",
      "away": "TUR"
    },
    {
      "id": "unl-401861178",
      "group": "A3",
      "matchday": 6,
      "date": "2026-11-15",
      "kickoff": "2026-11-15T19:45Z",
      "home": "CRO",
      "away": "CZE"
    },
    {
      "id": "unl-401861180",
      "group": "C3",
      "matchday": 6,
      "date": "2026-11-16",
      "kickoff": "2026-11-16T15:00Z",
      "home": "FRO",
      "away": "MDA"
    },
    {
      "id": "unl-401861181",
      "group": "C3",
      "matchday": 6,
      "date": "2026-11-16",
      "kickoff": "2026-11-16T15:00Z",
      "home": "KAZ",
      "away": "SVK"
    },
    {
      "id": "unl-401861182",
      "group": "C4",
      "matchday": 6,
      "date": "2026-11-16",
      "kickoff": "2026-11-16T17:00Z",
      "home": "ISL",
      "away": "LUX"
    },
    {
      "id": "unl-401861183",
      "group": "C4",
      "matchday": 6,
      "date": "2026-11-16",
      "kickoff": "2026-11-16T17:00Z",
      "home": "EST",
      "away": "BUL"
    },
    {
      "id": "unl-401861184",
      "group": "D2",
      "matchday": 6,
      "date": "2026-11-16",
      "kickoff": "2026-11-16T17:00Z",
      "home": "LTU",
      "away": "LIE"
    },
    {
      "id": "unl-401861179",
      "group": "D1",
      "matchday": 6,
      "date": "2026-11-16",
      "kickoff": "2026-11-16T19:45Z",
      "home": "GIB",
      "away": "MLT"
    },
    {
      "id": "unl-401861185",
      "group": "A2",
      "matchday": 6,
      "date": "2026-11-16",
      "kickoff": "2026-11-16T19:45Z",
      "home": "GER",
      "away": "NED"
    },
    {
      "id": "unl-401861186",
      "group": "B1",
      "matchday": 6,
      "date": "2026-11-16",
      "kickoff": "2026-11-16T19:45Z",
      "home": "SUI",
      "away": "SCO"
    },
    {
      "id": "unl-401861187",
      "group": "B1",
      "matchday": 6,
      "date": "2026-11-16",
      "kickoff": "2026-11-16T19:45Z",
      "home": "MKD",
      "away": "SVN"
    },
    {
      "id": "unl-401861188",
      "group": "A2",
      "matchday": 6,
      "date": "2026-11-16",
      "kickoff": "2026-11-16T19:45Z",
      "home": "GRE",
      "away": "SRB"
    },
    {
      "id": "unl-401861189",
      "group": "A4",
      "matchday": 6,
      "date": "2026-11-17",
      "kickoff": "2026-11-17T19:45Z",
      "home": "WAL",
      "away": "POR"
    },
    {
      "id": "unl-401861190",
      "group": "B2",
      "matchday": 6,
      "date": "2026-11-17",
      "kickoff": "2026-11-17T19:45Z",
      "home": "UKR",
      "away": "GEO"
    },
    {
      "id": "unl-401861191",
      "group": "B2",
      "matchday": 6,
      "date": "2026-11-17",
      "kickoff": "2026-11-17T19:45Z",
      "home": "HUN",
      "away": "NIR"
    },
    {
      "id": "unl-401861192",
      "group": "B3",
      "matchday": 6,
      "date": "2026-11-17",
      "kickoff": "2026-11-17T19:45Z",
      "home": "IRL",
      "away": "KOS"
    },
    {
      "id": "unl-401861193",
      "group": "B3",
      "matchday": 6,
      "date": "2026-11-17",
      "kickoff": "2026-11-17T19:45Z",
      "home": "ISR",
      "away": "AUT"
    },
    {
      "id": "unl-401861194",
      "group": "A4",
      "matchday": 6,
      "date": "2026-11-17",
      "kickoff": "2026-11-17T19:45Z",
      "home": "DEN",
      "away": "NOR"
    },
    {
      "id": "unl-401861195",
      "group": "B4",
      "matchday": 6,
      "date": "2026-11-17",
      "kickoff": "2026-11-17T19:45Z",
      "home": "POL",
      "away": "SWE"
    },
    {
      "id": "unl-401861196",
      "group": "B4",
      "matchday": 6,
      "date": "2026-11-17",
      "kickoff": "2026-11-17T19:45Z",
      "home": "BIH",
      "away": "ROU"
    }
  ],
  "knockoutRounds": [],
  "knockoutTracks": [
    {
      "id": "championship",
      "label": "Championship",
      "roundIds": [
        "qf",
        "sf",
        "third-place",
        "final"
      ],
      "pendingStages": [
        {
          "id": "qf",
          "label": "Quarter-finals",
          "window": "25–30 Mar 2027",
          "pools": [
            {
              "label": "League A group winners"
            },
            {
              "label": "League A group runners-up"
            }
          ]
        },
        {
          "id": "sf",
          "label": "Semi-finals",
          "window": "9–13 Jun 2027",
          "pools": [
            {
              "label": "Quarter-final winners"
            }
          ]
        },
        {
          "id": "third-place",
          "label": "Third-place match",
          "window": "13 Jun 2027",
          "pools": [
            {
              "label": "Semi-final losers"
            }
          ]
        },
        {
          "id": "final",
          "label": "Final",
          "window": "13 Jun 2027",
          "pools": [
            {
              "label": "Semi-final winners"
            }
          ]
        }
      ]
    },
    {
      "id": "promotion",
      "label": "Promotion / relegation",
      "roundIds": [
        "ab-playoff",
        "bc-playoff"
      ],
      "pendingStages": [
        {
          "id": "ab-playoff",
          "label": "League A/B play-offs",
          "window": "25–30 Mar 2027",
          "pools": [
            {
              "label": "League A play-off teams"
            },
            {
              "label": "League B runners-up"
            }
          ]
        },
        {
          "id": "bc-playoff",
          "label": "League B/C play-offs",
          "window": "25–30 Mar 2027",
          "pools": [
            {
              "label": "League B fourth-place teams"
            },
            {
              "label": "League C runners-up"
            }
          ]
        }
      ]
    }
  ]
}

export const unl2026: Tournament = {
  ...generated,
  teams: pickNationalTeams(["ITA","BEL","TUR","FRA","NED","GRE","GER","SRB","ESP","ENG","CZE","CRO","NOR","DEN","POR","WAL","MKD","SVN","SUI","SCO","UKR","HUN","GEO","NIR","ISR","AUT","IRL","KOS","BIH","SWE","POL","ROU","FIN","BLR","ALB","SMR","CYP","LVA","ARM","MNE","FRO","SVK","MDA","KAZ","EST","BUL","ISL","LUX","MLT","AND","GIB","LTU","AZE","LIE"]),
  groupMatches: generated.groupMatches.map((match) => ({
    ...match,
    ...(unl2026Videos[match.id] ? { videos: unl2026Videos[match.id] } : {}),
  })),
  knockoutRounds: generated.knockoutRounds.map((round) => ({
    ...round,
    matches: round.matches.map((match) => ({
      ...match,
      ...(unl2026Videos[match.id] ? { videos: unl2026Videos[match.id] } : {}),
    })),
  })),
}
