import type { HighlightVideo } from '../types'

/**
 * Auto-curated FOX Nations League cuts. Append-only; generated by
 * scripts/curate-nations-videos.ts after deterministic and trust gates pass.
 */
export const unl2026Videos: Record<string, HighlightVideo[]> = {
  'unl-401861044': [{ youtubeId: 'p88LkHIdxSY', kind: 'normal', durationSeconds: 588 }],
  'unl-401861046': [{ youtubeId: '7HyI8gieBfk', kind: 'extended', durationSeconds: 672 }],
}
