import type { HighlightVideo } from '../types'

/**
 * Auto-curated FOX Soccer Nations League cuts. Append-only; generated by
 * scripts/curate-nations-videos.ts after deterministic and trust gates pass.
 */
export const unl2026Videos: Record<string, HighlightVideo[]> = {}
