import type { HighlightVideo } from '../types'

/**
 * Auto-curated FOX and TUDN USA Nations League cuts. Append-only; generated by
 * scripts/curate-nations-videos.ts after deterministic and trust gates pass.
 */
export const unl2026Videos: Record<string, HighlightVideo[]> = {
  'unl-401861041': [{ youtubeId: 'VW2NXp9RaOE', kind: 'normal', durationSeconds: 886, publisher: 'tudn' }],
  'unl-401861042': [{ youtubeId: 'QtC18hzZt6Q', kind: 'normal', durationSeconds: 914, publisher: 'tudn' }],
  'unl-401861044': [{ youtubeId: 'p88LkHIdxSY', kind: 'normal', durationSeconds: 588 }],
  'unl-401861045': [{ youtubeId: 'eJZca-jevHg', kind: 'normal', durationSeconds: 917, publisher: 'tudn' }],
  'unl-401861046': [{ youtubeId: '7HyI8gieBfk', kind: 'extended', durationSeconds: 672 }],
  'unl-401861047': [{ youtubeId: 'FgtW1uYhuZU', kind: 'normal', durationSeconds: 918, publisher: 'tudn' }],
  'unl-401861048': [{ youtubeId: 'bdzcj-YDhyQ', kind: 'normal', durationSeconds: 894, publisher: 'tudn' }],
  'unl-401861049': [{ youtubeId: 'GLtiyDGr6V8', kind: 'normal', durationSeconds: 918, publisher: 'tudn' }],
  'unl-401861050': [{ youtubeId: '4tcE0-hdtQE', kind: 'normal', durationSeconds: 908, publisher: 'tudn' }],
  'unl-401861052': [{ youtubeId: '3HwX3l_ru3Q', kind: 'extended', durationSeconds: 952 }],
}
