/**
 * The team mark: a club crest, or a rounded-rectangle flag badge, or a
 * monogram, in that order.
 *
 * Flags are rounded rectangles — the professional football-product look
 * (FotMob/Sofascore/FIFA). Rectangles keep real flag proportions and detail
 * that circle-cropping mangled (Spain's crest in a porthole), and the shape
 * contrast means a circular play button between two flags can never read as
 * a row of three tokens.
 *
 * Crests are not flag-shaped, so they do not get that treatment. A crest is an
 * irregular silhouette on transparency; a 4:3 rounded box with curvature
 * shading would put a glass rectangle around a shield and clip its point. They
 * render in a square box with `object-fit: contain`, no radius and no sheen —
 * shape and rim do the work the badge chrome does for flags.
 *
 * Assets: flags are vendored flag-icons 4x3 SVGs
 * (https://github.com/lipis/flag-icons, MIT) in src/assets/flags, one per
 * national TeamId. Crests are the clubs' own marks in src/assets/crests, one
 * WebP per club slug, generated by scripts/fetch-crests.ts from ESPN's logo
 * CDN — see that file for why club badges are used and why they ship small.
 *
 * Crests are raster where flags are vector, which is the one asymmetry here.
 * It costs nothing visible: they are drawn at ~1em and stored at 96px, so even
 * a 3x phone has pixels to spare, and the whole set is 330 KB against 672 KB
 * of flags.
 *
 * Both are sized in `em` (flags height 1em/width 4:3, crests 1.05em square) so
 * they inherit whatever font-size the surrounding flag class already sets —
 * the same knob that sized the emoji.
 *
 * The crest box is styled inline rather than from App.css on purpose: this
 * file is imported by the component smoke tests, which run it under plain Node
 * where a `.css` import would throw, and App.css belongs to another workspace.
 * The `crest-badge` class is still on the wrapper so stylesheet rules can hang
 * off it later.
 */
import type { CSSProperties } from 'react'
import type { Team } from '../data/types'

// import.meta.glob is Vite-only; the component smoke tests run this file under
// plain Node (tsx), where the call throws — there the maps stay empty and
// every team takes the monogram fallback below. (A `typeof` guard doesn't
// work: Vite rewrites the glob call itself but leaves `typeof
// import.meta.glob` undefined at runtime.) Two globs, two try/catch blocks, so
// one missing directory can never empty the other.
let flagUrls: Record<string, string> = {}
try {
  flagUrls = import.meta.glob('../assets/flags/*.svg', {
    eager: true,
    query: '?url&no-inline',
    import: 'default',
  }) as Record<string, string>
} catch {
  // Node (tsx smoke tests): no bundler, no assets — monogram fallback.
}

let crestUrls: Record<string, string> = {}
try {
  crestUrls = import.meta.glob('../assets/crests/*.webp', {
    eager: true,
    query: '?url&no-inline',
    import: 'default',
  }) as Record<string, string>
} catch {
  // Node (tsx smoke tests): no bundler, no assets — monogram fallback.
}

const preloadedFlagHrefs = new Set<string>()
const warmedFlagImages = new Map<string, HTMLImageElement>()

function preloadFlagUrls(urls: string[]) {
  if (typeof document === 'undefined') return
  const existing = new Set(
    Array.from(document.querySelectorAll<HTMLLinkElement>('link[data-flag-preload]')).map(
      (link) => link.href,
    ),
  )
  for (const url of urls) {
    const href = new URL(url, document.baseURI).href
    if (preloadedFlagHrefs.has(href) || existing.has(href)) continue

    const link = document.createElement('link')
    link.rel = 'preload'
    link.as = 'image'
    link.href = url
    link.setAttribute('data-flag-preload', '')
    document.head.appendChild(link)
    existing.add(href)
    preloadedFlagHrefs.add(href)
  }
}

function warmFlagUrls(urls: string[]) {
  if (typeof document === 'undefined' || typeof Image === 'undefined') return

  for (const url of urls) {
    const href = new URL(url, document.baseURI).href
    let image = warmedFlagImages.get(href)

    if (!image) {
      image = new Image()
      image.decoding = 'sync'
      image.loading = 'eager'
      image.src = url
      warmedFlagImages.set(href, image)
    } else if (image.src !== href) {
      image.src = url
    }

    void image.decode?.().catch(() => {
      // Ignore decode races; the warm cache is best-effort and the visible img
      // still has the monogram fallback if a vendored asset is missing.
    })
  }
}

if (typeof window !== 'undefined') {
  // Crests warm alongside flags: a fixture row that pops its badges in one at
  // a time is the thing the preload exists to prevent, and the whole crest set
  // is half the weight of the flag set it rides along with.
  const urls = [...Object.values(flagUrls), ...Object.values(crestUrls)]
  const onVisibilityChange = () => {
    if (!document.hidden) warmFlagUrls(urls)
  }

  preloadFlagUrls(urls)
  warmFlagUrls(urls)
  document.addEventListener('visibilitychange', onVisibilityChange)

  import.meta.hot?.dispose(() => {
    document.removeEventListener('visibilitychange', onVisibilityChange)
    warmedFlagImages.clear()
  })
}

/* Square, contained, unrounded — see the header. Barely larger than the flag
   badge's 1em height: the art is trimmed to its own bounding box when it is
   generated, so unlike a padded crest it needs almost no compensation to carry
   the same visual weight as a flag. The drop-shadow matches the flag badge so
   crests and flags seat on a tint the same way. */
const crestBoxStyle: CSSProperties = {
  position: 'relative',
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  width: '1.05em',
  height: '1.05em',
  verticalAlign: '-0.125em',
  flexShrink: 0,
  lineHeight: 1,
  filter: 'drop-shadow(0 0.03em 0.07em rgba(0, 0, 0, 0.3))',
}

const crestImageStyle: CSSProperties = {
  display: 'block',
  width: '100%',
  height: '100%',
  objectFit: 'contain',
}

/* Last resort: the club's own short label. Sized off the box so it tracks
   whatever font-size the surrounding flag class set, and kept quiet enough
   that a missing asset reads as a placeholder rather than an error. */
const monogramStyle: CSSProperties = {
  fontSize: '0.42em',
  fontWeight: 700,
  letterSpacing: '0.02em',
  lineHeight: 1,
  color: 'rgba(233, 237, 245, 0.82)',
}

export function Flag({ team, className }: { team: Team; className?: string }) {
  const crestUrl = crestUrls[`../assets/crests/${team.id}.webp`]
  if (crestUrl) {
    const cls = className ? `crest-badge ${className}` : 'crest-badge'
    return (
      <span className={cls} style={crestBoxStyle}>
        <img
          src={crestUrl}
          alt=""
          draggable={false}
          decoding="sync"
          loading="eager"
          style={crestImageStyle}
        />
      </span>
    )
  }

  const flagUrl = flagUrls[`../assets/flags/${team.id}.svg`]
  if (flagUrl || team.flag) {
    const cls = className ? `flag-badge ${className}` : 'flag-badge'
    // A team without a vendored asset falls back to its emoji, so a new roster
    // entry degrades gracefully instead of rendering a broken image. The
    // wrapper span carries the curvature shading (an img can't host ::after).
    return (
      <span className={cls}>
        {flagUrl ? (
          <img src={flagUrl} alt="" draggable={false} decoding="sync" loading="eager" />
        ) : (
          team.flag
        )}
      </span>
    )
  }

  // Neither art nor emoji: a club whose crest hasn't landed yet. The monogram
  // keeps the row's rhythm; a club with no shortName renders nothing at all
  // rather than a broken box.
  if (!team.shortName) return null
  const cls = className ? `crest-badge ${className}` : 'crest-badge'
  return (
    <span className={cls} style={crestBoxStyle}>
      <span style={monogramStyle}>{team.shortName}</span>
    </span>
  )
}
