/**
 * The team mark: a club crest, or a rounded-rectangle flag badge, or a
 * monogram, in that order.
 *
 * Flags are rounded rectangles — the professional football-product look
 * (FotMob/Sofascore/FIFA). Rectangles keep real flag proportions and detail
 * that circle-cropping mangled (Spain's crest in a porthole), and the shape
 * contrast means a circular play button between two flags can never read as
 * a row of three tokens.
 *
 * Crests are not flag-shaped, so they do not get that treatment: a crest is an
 * irregular silhouette on transparency and it is drawn bare, in a square box.
 * An earlier pass put each one on a frosted disc to normalise the silhouettes,
 * and it read as a sticker laid over the artwork — every club has already
 * solved the problem of making its own badge legible. `.crest-badge` in
 * App.css is now size and a drop-shadow, nothing else.
 *
 * Assets: flags are vendored flag-icons 4x3 SVGs
 * (https://github.com/lipis/flag-icons, MIT) in src/assets/flags, one per
 * national TeamId. Crests are the clubs' own marks in src/assets/crests, one
 * WebP per club slug, generated by scripts/fetch-crests.ts from ESPN's logo
 * CDN — see that file for why club badges are used and how they are sized.
 *
 * Crests are raster where flags are vector, which is the one asymmetry here,
 * and it is the thing to watch when a crest is made bigger. They are stored at
 * 256px against a largest drawn size of 75 CSS px, which is one source pixel
 * per device pixel at DPR 3 — but the previous 96px only ever covered a 48px
 * mark, and once the crest grew past that every Retina screen was upscaling
 * and the badges went visibly soft. If a crest ever needs to be drawn larger
 * than 85 CSS px, that constant moves too. The set is ~0.9 MB against 672 KB
 * of flags.
 *
 * Both are sized in `em` (flags height 1em/width 4:3, crests square) so they
 * inherit whatever font-size the surrounding flag class already sets — the
 * same knob that sized the emoji.
 *
 * This file is imported by the component smoke tests, which run it under plain
 * Node where a `.css` import would throw — so it never imports a stylesheet.
 * It only emits the `crest-badge` / `flag-badge` class names, and App.css
 * dresses them; under Node the markup assertions pass unstyled.
 */
import type { Team } from '../data/types'

// import.meta.glob is Vite-only; the component smoke tests run this file under
// plain Node (tsx), where the call throws — there the maps stay empty and
// every team takes the monogram fallback below. (A `typeof` guard doesn't
// work: Vite rewrites the glob call itself but leaves `typeof
// import.meta.glob` undefined at runtime.) Two globs, two try/catch blocks, so
// one missing directory can never empty the other.
let flagUrls: Record<string, string> = {}
try {
  flagUrls = import.meta.glob('../assets/flags/*.svg', {
    eager: true,
    query: '?url&no-inline',
    import: 'default',
  }) as Record<string, string>
} catch {
  // Node (tsx smoke tests): no bundler, no assets — monogram fallback.
}

let crestUrls: Record<string, string> = {}
try {
  crestUrls = import.meta.glob('../assets/crests/*.webp', {
    eager: true,
    query: '?url&no-inline',
    import: 'default',
  }) as Record<string, string>
} catch {
  // Node (tsx smoke tests): no bundler, no assets — monogram fallback.
}

const preloadedFlagHrefs = new Set<string>()
const warmedFlagImages = new Map<string, HTMLImageElement>()

function preloadFlagUrls(urls: string[]) {
  if (typeof document === 'undefined') return
  const existing = new Set(
    Array.from(document.querySelectorAll<HTMLLinkElement>('link[data-flag-preload]')).map(
      (link) => link.href,
    ),
  )
  for (const url of urls) {
    const href = new URL(url, document.baseURI).href
    if (preloadedFlagHrefs.has(href) || existing.has(href)) continue

    const link = document.createElement('link')
    link.rel = 'preload'
    link.as = 'image'
    link.href = url
    link.setAttribute('data-flag-preload', '')
    document.head.appendChild(link)
    existing.add(href)
    preloadedFlagHrefs.add(href)
  }
}

function warmFlagUrls(urls: string[]) {
  if (typeof document === 'undefined' || typeof Image === 'undefined') return

  for (const url of urls) {
    const href = new URL(url, document.baseURI).href
    let image = warmedFlagImages.get(href)

    if (!image) {
      image = new Image()
      image.decoding = 'sync'
      image.loading = 'eager'
      image.src = url
      warmedFlagImages.set(href, image)
    } else if (image.src !== href) {
      image.src = url
    }

    void image.decode?.().catch(() => {
      // Ignore decode races; the warm cache is best-effort and the visible img
      // still has the monogram fallback if a vendored asset is missing.
    })
  }
}

if (typeof window !== 'undefined') {
  /*
   * Both sets warm on load — a fixture row that pops its badges in one at a
   * time is the thing this exists to prevent — but only the flags get a
   * `<link rel=preload>`.
   *
   * The two paths fetch the same bytes and dedupe into one request; the only
   * difference is priority. Crests are raster and are now 256px each, so the
   * set is ~0.9 MB, and sixty-six high-priority hints for it would queue ahead
   * of the JS that decides which two of them you actually need. As plain
   * `Image()` warming they fetch at normal priority, and the handful that are
   * genuinely on screen get promoted the moment their `<img>` mounts — which
   * is the right order. Flags are SVG, a few KB each, and stay on the fast
   * path.
   */
  const flags = Object.values(flagUrls)
  const urls = [...flags, ...Object.values(crestUrls)]
  const onVisibilityChange = () => {
    if (!document.hidden) warmFlagUrls(urls)
  }

  preloadFlagUrls(flags)
  warmFlagUrls(urls)
  document.addEventListener('visibilitychange', onVisibilityChange)

  import.meta.hot?.dispose(() => {
    document.removeEventListener('visibilitychange', onVisibilityChange)
    warmedFlagImages.clear()
  })
}


export function Flag({ team, className }: { team: Team; className?: string }) {
  const crestUrl = crestUrls[`../assets/crests/${team.id}.webp`]
  if (crestUrl) {
    const cls = className ? `crest-badge ${className}` : 'crest-badge'
    return (
      <span className={cls}>
        <img src={crestUrl} alt="" draggable={false} decoding="sync" loading="eager" />
      </span>
    )
  }

  const flagUrl = flagUrls[`../assets/flags/${team.id}.svg`]
  if (flagUrl || team.flag) {
    const cls = className ? `flag-badge ${className}` : 'flag-badge'
    // A team without a vendored asset falls back to its emoji, so a new roster
    // entry degrades gracefully instead of rendering a broken image. The
    // wrapper span carries the curvature shading (an img can't host ::after).
    return (
      <span className={cls}>
        {flagUrl ? (
          <img src={flagUrl} alt="" draggable={false} decoding="sync" loading="eager" />
        ) : (
          team.flag
        )}
      </span>
    )
  }

  // Neither art nor emoji: a club whose crest hasn't landed yet. The monogram
  // keeps the row's rhythm; a club with no shortName renders nothing at all
  // rather than a broken box.
  if (!team.shortName) return null
  const cls = className ? `crest-badge ${className}` : 'crest-badge'
  return (
    <span className={cls}>
      <span className="crest-monogram">{team.shortName}</span>
    </span>
  )
}
