#!/usr/bin/env node
/**
 * Automatic spoiler-safe entertainment summary curator for World Cup 2026.
 *
 *   npx tsx scripts/curate-entertainment.ts
 *   npx tsx scripts/curate-entertainment.ts --dry-run
 *
 * For finished matches missing an entertainment verdict, the curator:
 *   1. collects broad public-reaction snippets from public web search
 *   2. asks a model for a 1-2 sentence spoiler-safe entertainment synthesis
 *      plus a 1..5 entertainment rating
 *   3. validates the response conservatively
 *   4. writes it to src/data/wc2026-entertainment.ts
 *
 * FAIL CLOSED throughout: if the signal is weak, the response is unsafe, or
 * the model/API misbehaves, the match stays without a summary.
 */
import { writeFileSync } from 'fs'
import { pathToFileURL } from 'url'
import { tournaments } from '../src/data'
import type { EntertainmentRating, GroupMatch, KnockoutMatch } from '../src/data/types'
import { isPlayed } from '../src/logic/spoilers'
import { wc2026Entertainment, type EntertainmentEntry } from '../src/data/wc2026-entertainment'

const FILE = 'src/data/wc2026-entertainment.ts'
const MODEL = process.env.OPENAI_MODEL ?? 'gpt-5.4'
const EFFORT = process.env.OPENAI_REASONING_EFFORT ?? 'medium'
const BASE_URL = process.env.OPENAI_BASE_URL ?? 'https://api.openai.com/v1'
const dryRun = process.argv.includes('--dry-run')
const AI_ENABLED = Boolean(process.env.OPENAI_API_KEY)
const MIN_AGE_MINUTES = 150
const MAX_SEARCH_RESULTS = 6
const SEARCH_QUERIES_PER_MATCH = 2

const SYSTEM = `You write a spoiler-safe entertainment summary for a soccer match on a no-spoilers highlights site.

You are given broad public-reaction snippets about one match. These may include news reports, liveblogs, fan comments, forum posts, and other public reactions.

Write JSON only:
{"suitable": boolean, "rating": 1|2|3|4|5, "summary": string, "reason": string}

Rules:
- Write exactly 1 or 2 concise sentences when suitable is true.
- Help a user get a rough sense of whether the match felt entertaining, engaging, tense, lively, flat, open, cagey, or routine.
- Focus on entertainment value for the viewer, not tactical analysis and not recommendation language.
- Sound modest, not certain.
- Do not begin the summary with "Public reaction", "The overall reaction", or similar framing.

Do not mention or imply:
- the score
- goal count
- who won, lost, or drew
- late drama, equalizers, comebacks, upsets, penalties, red cards
- qualification or elimination stakes in a way that gives away the result
- whether the user should watch extended highlights, quick highlights, or skip
- strong recommendation language like "must-watch", "skip it", or "watch the longer highlights"

Set suitable to false if the snippets are too thin, too noisy, too contradictory, or you cannot write a spoiler-safe answer confidently.`

const SUMMARY_SPOILER_RE =
  /\b(win|won|loss|lose|lost|draw|drew|tie|tied|equali[sz]er|comeback|stoppage|penalt|red card|advance|advanced|qualif|eliminat|knockout|scoreline|late goal|late drama|last-minute|injury[- ]time|goalless|scoreless|winner)\b|(\d\s*[-–]\s*\d)|(\b\d+\s+goals?\b)|(\b(?:one|two|three|four|five|six|seven|eight|nine|ten)-goal\b)/i
const STARTS_WITH_REACTION_RE = /^(public reaction|the overall reaction|overall reaction|fan reaction)\b/i
const SEARCH_SKIP_RE =
  /\b(how to watch|tv channel|kick-off time|predicted line-ups|predicted lineups|highlights?|watch live|preview)\b/i

type AnyMatch = GroupMatch | KnockoutMatch

interface SearchSnippet {
  title: string
  snippet: string
  url: string
  domain: string
}

interface ModelVerdict {
  suitable: boolean
  rating: EntertainmentRating
  summary: string
  reason: string
}

const t = tournaments.wc2026

function nowMs(): number {
  return Date.now()
}

function kickoffMs(m: AnyMatch): number {
  return new Date(m.kickoff ?? `${m.date}T00:00:00Z`).getTime()
}

function playableTeams(m: AnyMatch): [string, string] | null {
  if ('group' in m) return [t.teams[m.home].name, t.teams[m.away].name]
  if (!m.homeTeam || !m.awayTeam) return null
  return [t.teams[m.homeTeam].name, t.teams[m.awayTeam].name]
}

export function loadEntertainment(): Record<string, EntertainmentEntry> {
  return { ...wc2026Entertainment }
}

function serializeEntertainment(map: Record<string, EntertainmentEntry>): string {
  const ids = Object.keys(map).sort()
  const header = `import type { EntertainmentRating } from './types'

export interface EntertainmentEntry {
  entertainmentSummary: string
  entertainmentRating: EntertainmentRating
}

/**
 * Auto-curated entertainment summaries keyed by match id.
 *
 * GENERATED by scripts/curate-entertainment.ts — do not edit by hand.
 * Kept separate from wc2026.ts so the curation bot can own this file
 * end-to-end without touching the hand-maintained tournament data.
 */
`
  if (ids.length === 0) {
    return `${header}export const wc2026Entertainment: Record<string, EntertainmentEntry> = {}\n`
  }
  const body = ids
    .map((id) => `  ${JSON.stringify(id)}: {\n    entertainmentSummary: ${JSON.stringify(map[id].entertainmentSummary)},\n    entertainmentRating: ${map[id].entertainmentRating},\n  },`)
    .join('\n')
  return `${header}export const wc2026Entertainment: Record<string, EntertainmentEntry> = {\n${body}\n}\n`
}

function decodeHtml(text: string): string {
  return text
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n)))
    .replace(/&#x([0-9a-f]+);/gi, (_, n) => String.fromCharCode(parseInt(n, 16)))
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/<[^>]+>/g, '')
    .replace(/\s+/g, ' ')
    .trim()
}

function resolvedDdgUrl(raw: string): string {
  const href = raw.startsWith('//') ? `https:${raw}` : raw
  try {
    const url = new URL(href)
    const uddg = url.searchParams.get('uddg')
    return uddg ? decodeURIComponent(uddg) : href
  } catch {
    return href
  }
}

async function searchDuckDuckGo(query: string, max: number): Promise<SearchSnippet[]> {
  const url = `https://duckduckgo.com/html/?q=${encodeURIComponent(query)}`
  const res = await fetch(url, { headers: { 'User-Agent': 'Mozilla/5.0' } })
  if (!res.ok) throw new Error(`duckduckgo ${res.status}`)
  const html = await res.text()
  const out: SearchSnippet[] = []
  const re =
    /<a rel="nofollow" class="result__a" href="([^"]+)">([\s\S]*?)<\/a>[\s\S]*?<a class="result__snippet" href="[^"]+">([\s\S]*?)<\/a>/g
  for (const m of html.matchAll(re)) {
    const title = decodeHtml(m[2])
    const snippet = decodeHtml(m[3])
    if (!title || !snippet) continue
    if (SEARCH_SKIP_RE.test(title) || SEARCH_SKIP_RE.test(snippet)) continue
    const url = resolvedDdgUrl(m[1])
    let domain = ''
    try {
      domain = new URL(url).hostname.replace(/^www\./, '')
    } catch {
      continue
    }
    if (/(youtube\.com|youtu\.be|foxsports\.com)$/.test(domain)) continue
    out.push({ title, snippet, url, domain })
    if (out.length >= max) break
  }
  return out
}

async function gatherSnippets(home: string, away: string): Promise<SearchSnippet[]> {
  const queries = [
    `${home} ${away} World Cup 2026 reaction`,
    `${home} ${away} World Cup 2026 fan reaction`,
  ].slice(0, SEARCH_QUERIES_PER_MATCH)
  const seen = new Set<string>()
  const out: SearchSnippet[] = []
  for (const query of queries) {
    let results: SearchSnippet[] = []
    try {
      results = await searchDuckDuckGo(query, MAX_SEARCH_RESULTS)
    } catch (e) {
      console.error(`search failed for "${query}": ${e}`)
      continue
    }
    for (const item of results) {
      const key = `${item.domain}|${item.title.toLowerCase()}`
      if (seen.has(key)) continue
      seen.add(key)
      out.push(item)
    }
  }
  return out.slice(0, 8)
}

async function callModel(body: Record<string, unknown>): Promise<Response> {
  return fetch(`${BASE_URL}/chat/completions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
    },
    body: JSON.stringify(body),
  })
}

export function parseVerdict(text: string): ModelVerdict {
  const start = text.indexOf('{')
  const end = text.lastIndexOf('}')
  if (start === -1 || end === -1) throw new Error('no JSON in model reply')
  const obj = JSON.parse(text.slice(start, end + 1)) as Partial<ModelVerdict>
  if (typeof obj.suitable !== 'boolean') throw new Error('missing suitable')
  if (!Number.isInteger(obj.rating) || obj.rating < 1 || obj.rating > 5) throw new Error('bad rating')
  if (typeof obj.summary !== 'string' || typeof obj.reason !== 'string') throw new Error('bad strings')
  return {
    suitable: obj.suitable,
    rating: obj.rating as EntertainmentRating,
    summary: obj.summary.trim(),
    reason: obj.reason.trim(),
  }
}

export function isSafeSummary(summary: string): boolean {
  if (!summary) return false
  if (STARTS_WITH_REACTION_RE.test(summary)) return false
  if (SUMMARY_SPOILER_RE.test(summary)) return false
  const sentenceCount = summary
    .split(/[.!?]+/)
    .map((s) => s.trim())
    .filter(Boolean).length
  return sentenceCount >= 1 && sentenceCount <= 2
}

async function summarizeMatch(home: string, away: string, snippets: SearchSnippet[]): Promise<ModelVerdict> {
  const messages = [
    { role: 'system', content: SYSTEM },
    {
      role: 'user',
      content:
        `MATCH: ${home} vs ${away}\n` +
        `SNIPPETS:\n` +
        snippets
          .map((s, i) => `${i + 1}. [${s.domain}] ${s.title} — ${s.snippet}`)
          .join('\n'),
    },
  ]
  const rich = {
    model: MODEL,
    messages,
    reasoning_effort: EFFORT,
    response_format: { type: 'json_object' },
  }
  let res = await callModel(rich)
  if (res.status === 400) res = await callModel({ model: MODEL, messages })
  if (!res.ok) throw new Error(`API ${res.status}: ${(await res.text()).slice(0, 150)}`)
  const data = (await res.json()) as { choices?: { message?: { content?: string } }[] }
  const text = data.choices?.[0]?.message?.content
  if (!text) throw new Error('empty model reply')
  return parseVerdict(text)
}

const allMatches: AnyMatch[] = [
  ...t.groupMatches,
  ...t.knockoutRounds.flatMap((r) => r.matches),
]

export function shouldCurate(
  m: AnyMatch,
  entertainment: Record<string, EntertainmentEntry>,
  options: {
    aiEnabled?: boolean
    now?: number
    minAgeMinutes?: number
  } = {},
): boolean {
  const aiEnabled = options.aiEnabled ?? AI_ENABLED
  const now = options.now ?? nowMs()
  const minAgeMinutes = options.minAgeMinutes ?? MIN_AGE_MINUTES

  if (!aiEnabled) return false
  if (!isPlayed(m)) return false
  if (entertainment[m.id]) return false
  const teams = playableTeams(m)
  if (!teams) return false
  const ageMinutes = (now - kickoffMs(m)) / 60000
  return ageMinutes >= minAgeMinutes
}

async function run() {
  const entertainment = loadEntertainment()
  const candidates = allMatches.filter((m) => shouldCurate(m, entertainment))

  if (!AI_ENABLED) {
    console.log('no OPENAI_API_KEY — skipping entertainment curation')
    return
  }

  if (candidates.length === 0) {
    console.log('no entertainment summaries to curate')
    return
  }

  const added: string[] = []
  for (const match of candidates) {
    const teams = playableTeams(match)
    if (!teams) continue
    const [home, away] = teams
    const snippets = await gatherSnippets(home, away)
    if (snippets.length < 4) {
      console.log(`skip ${match.id}: only ${snippets.length} usable snippets`)
      continue
    }
    try {
      const verdict = await summarizeMatch(home, away, snippets)
      if (!verdict.suitable) {
        console.log(`skip ${match.id}: ${verdict.reason || 'model marked unsuitable'}`)
        continue
      }
      if (!isSafeSummary(verdict.summary)) {
        console.log(`skip ${match.id}: summary failed safety validation`)
        continue
      }
      entertainment[match.id] = {
        entertainmentSummary: verdict.summary,
        entertainmentRating: verdict.rating,
      }
      added.push(match.id)
      console.log(`added ${match.id}`)
    } catch (e) {
      console.error(`skip ${match.id}: ${e}`)
    }
    await new Promise((r) => setTimeout(r, 250))
  }

  if (added.length === 0) {
    console.log('no entertainment summaries added')
    return
  }

  if (!dryRun) writeFileSync(FILE, serializeEntertainment(entertainment))
  console.log(`${dryRun ? 'would add' : 'added'} ${added.length} entertainment summary(s):`)
  for (const id of added) console.log(`  ${id}`)
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  run().catch((e) => {
    console.error(e)
    process.exit(1)
  })
}
