/**
 * Regenerate the UEFA Nations League 2026/27 snapshot from ESPN, but only
 * after it agrees with every row in UEFA's independently checked manifest.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { buildNationsSeason } from './espn-nations-lib'
import { UNL_2026_OFFICIAL_FIXTURES } from '../src/data/nations/unl-2026-official'
import type { Tournament } from '../src/data/types'

const SCOREBOARD = 'https://site.api.espn.com/apis/site/v2/sports/soccer/uefa.nations/scoreboard'
const STANDINGS = 'https://site.api.espn.com/apis/v2/sports/soccer/uefa.nations/standings'
const outputUrl = new URL('../src/data/nations/unl-2026.ts', import.meta.url)

async function fetchJson(url: string): Promise<unknown> {
  const response = await fetch(url)
  if (!response.ok) throw new Error(`${response.status} from ${url}`)
  return response.json()
}

const [scoreboard2026, scoreboard2027, standings] = await Promise.all([
  fetchJson(`${SCOREBOARD}?dates=2026&limit=1000`),
  fetchJson(`${SCOREBOARD}?dates=2027&limit=1000`),
  fetchJson(STANDINGS),
]) as [{ events?: unknown[] }, { events?: unknown[] }, Parameters<typeof buildNationsSeason>[0]['standings']]

let previous: Tournament | undefined
if (existsSync(outputUrl)) {
  // The pure builder accepts the prior snapshot so later-stage publication can
  // be all-or-nothing. Avoid importing generated TypeScript into its own writer.
  const source = readFileSync(outputUrl, 'utf8')
  if (source.includes('export const unl2026')) previous = undefined
}

const result = buildNationsSeason({
  standings,
  events: [...(scoreboard2026.events ?? []), ...(scoreboard2027.events ?? [])] as Parameters<typeof buildNationsSeason>[0]['events'],
  official: UNL_2026_OFFICIAL_FIXTURES,
  previous,
})
if (result.audit.errors.length) {
  throw new Error(`Nations League ingest rejected:\n${result.audit.errors.map((error) => `- ${error}`).join('\n')}`)
}

const { teams, ...generated } = result.tournament
const teamIds = Object.keys(teams)
const source = `/**\n * GENERATED by scripts/espn-nations.ts. Do not edit by hand.\n * Fixtures are accepted only after matching unl-2026-official.ts.\n */\nimport type { Tournament } from '../types'\nimport { pickNationalTeams } from '../national-teams'\nimport { unl2026Videos } from './unl-2026-videos'\n\nconst generated: Omit<Tournament, 'teams'> = ${JSON.stringify(generated, null, 2)}\n\nexport const unl2026: Tournament = {\n  ...generated,\n  teams: pickNationalTeams(${JSON.stringify(teamIds)}),\n  groupMatches: generated.groupMatches.map((match) => ({\n    ...match,\n    ...(unl2026Videos[match.id] ? { videos: unl2026Videos[match.id] } : {}),\n  })),\n}\n`
writeFileSync(outputUrl, source)
console.log(`${teamIds.length} teams, ${generated.groups.length} groups, ${generated.groupMatches.length} fixtures, ${result.audit.errors.length} source disagreements`)
for (const notice of result.audit.notices) console.log(`notice: ${notice}`)
