/**
 * Regenerate the UEFA Nations League 2026/27 snapshot from ESPN, but only
 * after it agrees with every row in UEFA's independently checked manifest.
 */
import { existsSync, renameSync, rmSync, writeFileSync } from 'node:fs'
import { buildNationsSeason } from './espn-nations-lib'
import { UNL_2026_OFFICIAL_FIXTURES } from '../src/data/nations/unl-2026-official'
import type { Tournament } from '../src/data/types'

const SCOREBOARD = 'https://site.api.espn.com/apis/site/v2/sports/soccer/uefa.nations/scoreboard'
const STANDINGS = 'https://site.api.espn.com/apis/v2/sports/soccer/uefa.nations/standings'
const outputUrl = new URL('../src/data/nations/unl-2026.ts', import.meta.url)
const dryRun = process.argv.includes('--dry-run')

async function fetchJson(url: string): Promise<unknown> {
  const response = await fetch(url)
  if (!response.ok) throw new Error(`${response.status} from ${url}`)
  return response.json()
}

const [scoreboard2026, scoreboard2027, standings] = await Promise.all([
  fetchJson(`${SCOREBOARD}?dates=2026&limit=1000`),
  fetchJson(`${SCOREBOARD}?dates=2027&limit=1000`),
  fetchJson(STANDINGS),
]) as [{ events?: unknown[] }, { events?: unknown[] }, Parameters<typeof buildNationsSeason>[0]['standings']]

let previous: Tournament | undefined
if (existsSync(outputUrl)) {
  const current = await import(`${outputUrl.href}?previous=${Date.now()}`) as { unl2026?: Tournament }
  previous = current.unl2026
}

const result = buildNationsSeason({
  standings,
  events: [...(scoreboard2026.events ?? []), ...(scoreboard2027.events ?? [])] as Parameters<typeof buildNationsSeason>[0]['events'],
  official: UNL_2026_OFFICIAL_FIXTURES,
  previous,
})
const auditFile = process.env.NATIONS_AUDIT_FILE
if (auditFile) {
  const lines = [
    '# Nations League ingest audit',
    '',
    `- fixtures: ${result.tournament.groupMatches.length}`,
    `- errors: ${result.audit.errors.length}`,
    `- notices: ${result.audit.notices.length}`,
    '',
    ...result.audit.errors.map((error) => `- error: ${error}`),
    ...result.audit.notices.map((notice) => `- notice: ${notice}`),
    '',
  ]
  writeFileSync(auditFile, lines.join('\n'))
}

if (result.audit.errors.length) {
  throw new Error(`Nations League ingest rejected:\n${result.audit.errors.map((error) => `- ${error}`).join('\n')}`)
}

const { teams, ...generated } = result.tournament
const teamIds = Object.keys(teams)
const source = `/**\n * GENERATED by scripts/espn-nations.ts. Do not edit by hand.\n * Fixtures are accepted only after matching unl-2026-official.ts.\n */\nimport type { Tournament } from '../types'\nimport { pickNationalTeams } from '../national-teams'\nimport { unl2026Videos } from './unl-2026-videos'\n\nconst generated: Omit<Tournament, 'teams'> = ${JSON.stringify(generated, null, 2)}\n\nexport const unl2026: Tournament = {\n  ...generated,\n  teams: pickNationalTeams(${JSON.stringify(teamIds)}),\n  groupMatches: generated.groupMatches.map((match) => ({\n    ...match,\n    ...(unl2026Videos[match.id] ? { videos: unl2026Videos[match.id] } : {}),\n  })),\n  knockoutRounds: generated.knockoutRounds.map((round) => ({\n    ...round,\n    matches: round.matches.map((match) => ({\n      ...match,\n      ...(unl2026Videos[match.id] ? { videos: unl2026Videos[match.id] } : {}),\n    })),\n  })),\n}\n`
if (!dryRun) {
  const temporaryUrl = new URL(`./unl-2026.ts.tmp-${process.pid}`, outputUrl)
  try {
    writeFileSync(temporaryUrl, source)
    renameSync(temporaryUrl, outputUrl)
  } finally {
    if (existsSync(temporaryUrl)) rmSync(temporaryUrl)
  }
}
console.log(`${dryRun ? 'dry run: ' : ''}${teamIds.length} teams, ${generated.groups.length} groups, ${generated.groupMatches.length} fixtures, ${result.audit.errors.length} source disagreements`)
for (const notice of result.audit.notices) console.log(`notice: ${notice}`)
