import type { Tournament } from './types'

export interface TableZone {
  /** Inclusive, 1-based table positions this band covers. */
  from: number
  to: number
  /** What the band means. The colour is chosen from this, never passed in. */
  kind: 'qualify' | 'playoff' | 'drop'
  /** Legend text. */
  label: string
}

/**
 * Where the lines fall in a single-table competition — the top-four bar and
 * the relegation bar every league table in the world draws, and which ours
 * was missing.
 *
 * This lives here, keyed by competition, rather than in the season data:
 * those files are generated by scripts/espn-club.ts and rewritten whole on
 * every run, so a hand-added field would be lost silently on the next ingest.
 *
 * Only bands nobody argues about. A league's European places below the
 * Champions League spots move with whoever wins the domestic cups, so any
 * line drawn for the Europa or Conference League is wrong in some seasons —
 * two honest bands beat five that need an asterisk.
 */
export function tableZones(t: Tournament): TableZone[] {
  const size = t.groups[0]?.teams.length ?? 0
  const competition = t.id.replace(/-\d{4}$/, '')

  switch (competition) {
    case 'eng1':
    case 'esp1':
      // Three down is the shape of both leagues; the count is read from the
      // data so a 18- or 22-team season still marks the right rows.
      if (size < 8) return []
      return [
        { from: 1, to: 4, kind: 'qualify', label: 'Champions League' },
        { from: size - 2, to: size, kind: 'drop', label: 'Relegation' },
      ]
    case 'ucl':
      // League-phase format: the top eight go straight to the last 16,
      // 9th–24th play a two-legged playoff for the other eight places. The
      // rest are out, which needs no band — the absence of one says it.
      if (size < 24) return []
      return [
        { from: 1, to: 8, kind: 'qualify', label: 'Last 16' },
        { from: 9, to: 24, kind: 'playoff', label: 'Knockout playoff' },
      ]
    default:
      return []
  }
}

export function zoneAt(zones: TableZone[], rank: number): TableZone | null {
  return zones.find((z) => rank >= z.from && rank <= z.to) ?? null
}
