import type { HighlightVideo } from './types'

/**
 * Auto-curated FOX highlight cuts, keyed by match id.
 *
 * GENERATED by scripts/curate-videos.ts — do not edit by hand. Entries are
 * appended automatically as FOX publishes spoiler-free highlights and each one
 * clears the curator's deterministic guards + AI spoiler check. Kept separate
 * from wc2026.ts so the bot owns one file end-to-end and never has to edit the
 * hand-maintained tournament data. src/data/index.ts merges these in.
 */
export const wc2026Videos: Record<string, HighlightVideo[]> = {}
