import type { HighlightVideo } from './types'

/**
 * Auto-curated FOX highlight cuts, keyed by match id.
 *
 * GENERATED by scripts/curate-videos.ts — do not edit by hand. Entries are
 * appended automatically as FOX publishes spoiler-free highlights and each one
 * clears the curator's deterministic guards + AI spoiler check. Kept separate
 * from wc2026.ts so the bot owns one file end-to-end and never has to edit the
 * hand-maintained tournament data. src/data/index.ts merges these in.
 */
export const wc2026Videos: Record<string, HighlightVideo[]> = {
  'E2': [{ youtubeId: 'j6uB9LcLMms', kind: 'extended', durationSeconds: 1304 }, { youtubeId: 'pBk8BjA-X4Y', kind: 'normal', durationSeconds: 524 }],
  'F1': [{ youtubeId: 'SaTyQMmOpPM', kind: 'extended', durationSeconds: 1264 }, { youtubeId: 'm7sQP_AZ5vM', kind: 'normal', durationSeconds: 512 }],
  'F2': [{ youtubeId: 'F47z0suCV7Y', kind: 'extended', durationSeconds: 1266 }, { youtubeId: 'MWsgrEPIni4', kind: 'normal', durationSeconds: 523 }],
  'H1': [{ youtubeId: 'YnWF8IMcqgg', kind: 'normal', durationSeconds: 488 }, { youtubeId: 'wzKYVElYRrw', kind: 'extended', durationSeconds: 1329 }],
}
