import type { HighlightVideo } from './types'

/**
 * Auto-curated FOX highlight cuts, keyed by match id.
 *
 * GENERATED by scripts/curate-videos.ts — do not edit by hand. Entries are
 * appended automatically as FOX publishes spoiler-free highlights and each one
 * clears the curator's deterministic guards + AI spoiler check. Kept separate
 * from wc2026.ts so the bot owns one file end-to-end and never has to edit the
 * hand-maintained tournament data. src/data/index.ts merges these in.
 */
export const wc2026Videos: Record<string, HighlightVideo[]> = {
  'A3': [{ youtubeId: 'jijCaWH_IxM', kind: 'extended', durationSeconds: 934 }],
  'A4': [{ youtubeId: 'F1sMvm6D-0Y', kind: 'extended', durationSeconds: 937 }],
  'B3': [{ youtubeId: 'v08lQx6pThk', kind: 'extended', durationSeconds: 1046 }],
  'B4': [{ youtubeId: 'vz9OTeU6gTM', kind: 'extended', durationSeconds: 1012 }],
  'C3': [{ youtubeId: 'wff2tvitS-s', kind: 'extended', durationSeconds: 903 }],
  'C4': [{ youtubeId: 'BphiVajPsFc', kind: 'extended', durationSeconds: 947 }],
  'D3': [{ youtubeId: '1gMiT5r-K7Q', kind: 'extended', durationSeconds: 1000 }],
  'D4': [{ youtubeId: 'HrbIda-C9SE', kind: 'extended', durationSeconds: 964 }],
  'E2': [{ youtubeId: 'j6uB9LcLMms', kind: 'extended', durationSeconds: 1304 }, { youtubeId: 'pBk8BjA-X4Y', kind: 'normal', durationSeconds: 524 }],
  'E3': [{ youtubeId: 'EL9nHScp4bk', kind: 'extended', durationSeconds: 957 }],
  'E4': [{ youtubeId: '_JQLeADlzXM', kind: 'extended', durationSeconds: 933 }],
  'F1': [{ youtubeId: 'SaTyQMmOpPM', kind: 'extended', durationSeconds: 1264 }, { youtubeId: 'm7sQP_AZ5vM', kind: 'normal', durationSeconds: 512 }],
  'F2': [{ youtubeId: 'F47z0suCV7Y', kind: 'extended', durationSeconds: 1266 }, { youtubeId: 'MWsgrEPIni4', kind: 'normal', durationSeconds: 523 }],
  'F3': [{ youtubeId: 'IRllRLrG7Sg', kind: 'extended', durationSeconds: 990 }],
  'F4': [{ youtubeId: 'ATmlGGfCyBA', kind: 'extended', durationSeconds: 736 }],
  'G1': [{ youtubeId: 'o_3t0d8x9JY', kind: 'normal', durationSeconds: 537 }, { youtubeId: 'gQOgcN7_IZE', kind: 'extended', durationSeconds: 1403 }],
  'G2': [{ youtubeId: 'UZ_7qFbFYRY', kind: 'extended', durationSeconds: 1029 }],
  'G3': [{ youtubeId: 'YbiEe9pOV-s', kind: 'extended', durationSeconds: 891 }],
  'H1': [{ youtubeId: 'YnWF8IMcqgg', kind: 'normal', durationSeconds: 488 }, { youtubeId: 'wzKYVElYRrw', kind: 'extended', durationSeconds: 1329 }],
  'H2': [{ youtubeId: 'Tz9R1OYdTSs', kind: 'extended', durationSeconds: 1009 }],
  'H3': [{ youtubeId: 'w453UjgtQw4', kind: 'extended', durationSeconds: 918 }],
  'H4': [{ youtubeId: 'ZXvFKZM1nL4', kind: 'extended', durationSeconds: 1147 }],
  'I1': [{ youtubeId: 'SlmYDbzHqjg', kind: 'extended', durationSeconds: 1036 }],
  'I2': [{ youtubeId: 'ku1hsMdKDXQ', kind: 'extended', durationSeconds: 1080 }],
  'J1': [{ youtubeId: 'GtyuIf7zykA', kind: 'extended', durationSeconds: 786 }],
  'J2': [{ youtubeId: 'yOPRItttrPU', kind: 'extended', durationSeconds: 1135 }],
  'K1': [{ youtubeId: 'SjumRdNESKg', kind: 'extended', durationSeconds: 1105 }],
  'K2': [{ youtubeId: 'Qb3ipZFspnc', kind: 'extended', durationSeconds: 970 }],
  'L1': [{ youtubeId: 'lGoe9nxRfyU', kind: 'extended', durationSeconds: 1030 }],
  'L2': [{ youtubeId: 'hFO9DhasJ2A', kind: 'extended', durationSeconds: 985 }],
}
