import type { EntertainmentRating } from './types'

export interface EntertainmentEntry {
  entertainmentSummary: string
  entertainmentRating: EntertainmentRating
}

/**
 * Auto-curated entertainment summaries keyed by match id.
 *
 * GENERATED by scripts/curate-entertainment.ts — do not edit by hand.
 * Kept separate from wc2026.ts so the curation bot can own this file
 * end-to-end without touching the hand-maintained tournament data.
 */
export const wc2026Entertainment: Record<string, EntertainmentEntry> = {
  D5: {
    entertainmentSummary:
      'Lively and open for long stretches, with enough momentum shifts to keep it engaging. More entertaining than a routine group-stage watch.',
    entertainmentRating: 4,
  },
  D6: {
    entertainmentSummary:
      'More tense than open, with caution outweighing sustained drama. The intrigue seems to have come more from the atmosphere than from a steady run of memorable moments.',
    entertainmentRating: 2,
  },
  E5: {
    entertainmentSummary:
      'One of the more gripping matches of the day, with real intensity and long stretches of pressure. Engaging from early on rather than fading into something routine.',
    entertainmentRating: 5,
  },
  E6: {
    entertainmentSummary:
      'A steadier watch with a few sharp moments, but not one of the livelier matches on the slate. More controlled than dramatic overall.',
    entertainmentRating: 2,
  },
  F5: {
    entertainmentSummary:
      'Mixed at first, but warmer on the overall watch once it opened up. More tense and engaging than chaotic.',
    entertainmentRating: 3,
  },
  F6: {
    entertainmentSummary:
      'Mildly positive overall, mostly because it moved along and stayed reasonably watchable. More solid than electric.',
    entertainmentRating: 3,
  },
}
